Home work1 - completed
daarklight/VladislavProkopenko pull request #1
Opened 2021-06-14 21:17 UTC by daarklight

This is 1st trial.

2021-06-15 17:08 UTC, shoggy requested changes

2021-06-15 17:08 UTC, shoggy commented on pom.xml
> +      <version>7.4.0</version>
`properties` section is better place for versions

2021-06-15 17:08 UTC, shoggy commented on pom.xml
> +    </dependency>
What is this dependency required for?

2021-06-15 17:08 UTC, shoggy commented on pom.xml
> +    </plugins>
`maven-checkstyle-plugin` definition is missed

2021-06-15 17:08 UTC, shoggy commented on pom.xml
> +  </profiles>
Three profiles are required

2021-06-15 17:08 UTC, shoggy commented on src/test/java/ru/training/at/hw1/mainTestClasses/AdditionTest.java
> +        Calculator calculator = new Calculator();
Looks like SystemUnderTest-initialization, please move it to the appropriate place. Pay attention that all Test Classes have this point in common

2021-06-15 17:08 UTC, shoggy commented on src/test/java/ru/training/at/hw1/mainTestClasses/DivisionTest.java
> +        Assert.assertEquals(actualResult, expectedResult);
Double comparison is not strict and requires one additional parameter

2021-06-15 21:51 UTC, daarklight commented
This is 2nd trial. All comments were taken into account.

2021-06-22 16:52 UTC, shoggy approved these changes
Good work
In the next tasks please avoid `System.out` and magic numbers

2021-06-28 17:27 UTC, merged